### ISSUE TITLE
some values, when editing them, have less length | Also you should add a image, it would look cool, it wouldn't hurt anyone :)

### ISSUE THREAD

**Issue by MirayXS** [CrustySean/SplatEditorNX#1]
## Issue: Some values, when editing them, have less length
Example: Value is: **6003** *(4)*
> When editing this value, in SplatEditorNX shows **6** *(1)*

Alot of editable values do this, the equipped shoes is just an example, you can look for yourself to see which values have this bug

Screenshots:
![image](https://user-images.githubusercontent.com/55494819/158559622-037fef24-fad1-495f-bd4d-e91c0042304b.png)
> The value highlighted is the one i'm trying to edit

![image](https://user-images.githubusercontent.com/55494819/158559736-6aeb1120-73b1-4778-aa80-af73d7e79163.png)
> When trying to modify the value by inputting a new value it only shows one value to edit

## Suggestion: Also you should add a image, it would look cool, it wouldn't hurt anyone
As the suggestion says, a icon for the homebrew would be neat, it's because me (and maybe more people) don't like it when a homebrew has no icon. It's just a cosmetic thing though

**Comment by CrustySean** [comment]
Hi! Thanks for submitting this issue. So uhh that's my fault because I lefted some items to have the max length of just 1. I'll fix it as soon as I'll have some time.

Also regarding the images, the app automatically download the image based on the input you provided.

**Comment by MirayXS** [comment]
> Also regarding the images, the app automatically download the image based on the input you provided.

Oh' i think you misunderstanded me, i meant the icon that shows up in the homebrew menu
i'll take a photo later if i can, i'm out rn

**Comment by CrustySean** [comment]
oh, my bad, I probably forgot to run the script to download the app icon. I'll make sure to run it in the next release :p.

**Comment by MirayXS** [comment]
![image](https://user-images.githubusercontent.com/55494819/158607852-97657edf-bbe6-4fe9-8839-51686eea5059.png)

**Comment by MirayXS** [comment]
> oh, my bad, I probably forgot to run the script to download the app icon. I'll make sure to run it in the next release :p.

haha it's alright :))
